name: Deploy SH App to Production

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # -----------------------------------------
    # DOCKER HUB LOGIN
    # -----------------------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # -----------------------------------------
    # BUILD BACK IMAGE
    # -----------------------------------------
    - name: Build backend image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_BACK }}:latest ./back

    - name: Push backend image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_BACK }}:latest

    # -----------------------------------------
    # BUILD FRONT IMAGE
    # -----------------------------------------
    - name: Build frontend image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_FRONT }}:latest ./front

    - name: Push frontend image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_FRONT }}:latest

    # -----------------------------------------
    # SSH & DEPLOY
    # -----------------------------------------
    - name: SSH to server and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /apps/sh/app
          docker compose pull
          docker compose up -d --remove-orphans
